---
vault_domain: "arq.unb.br"
vault_hostname: "vault.{{ vault_domain }}"
vault_namespace: "vault"
vault_secret_name: "vault-tls"
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
temp_cert_path: "/tmp/vault-tls.crt"
temp_key_path: "/tmp/vault-tls.key"
temp_intermediate_path: "/tmp/vault-intermediate.pem"
temp_root_path: "/tmp/vault-gs_root.pem"
temp_ca_bundle_path: "/tmp/vault-ca-bundle.pem"
cert_file: "tls.crt"
key_file: "tls.key"
intermediate_cert_file: "intermediate.pem"
root_cert_file: "gs_root.pem"
