---
- name: Configurar o locale pt_BR.UTF-8
  community.general.locale_gen:
    name: pt_BR.UTF-8
    state: present

- name: Configurar o timezone para America/Sao_Paulo
  community.general.timezone:
    name: America/Sao_Paulo
