---
rancher_hostname: "rancher.arq.unb.br"
rancher_version: "2.8.0"
rancher_secret_name: "rancher-tls"
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
temp_cert_path: "/tmp/tls.crt"
temp_key_path: "/tmp/tls.key"
cert_file: "arq.unb.br.crt"
key_file: "arq.unb.br.key"
