---
rancher_hostname: "rancher.arq.unb.br"
rancher_version: "2.8.0"
rancher_secret_name: "rancher-tls"
rancher_admin_password: "admin"
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
temp_cert_path: "/tmp/tls.crt"
temp_key_path: "/tmp/tls.key"
temp_cert_chain_path: "/tmp/tls-chain.crt"
temp_intermediate_path: "/tmp/intermediate.pem"
temp_root_path: "/tmp/gs_root.pem"
cert_file: "tls.crt"
key_file: "tls.key"
intermediate_cert_file: "intermediate.pem"
root_cert_file: "gs_root.pem"
