---
- name: Create vault-secrets-operator namespace
  kubernetes.core.k8s:
    name: "{{ vault_operator_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
