---
- name: Setup Helm repository
  ansible.builtin.include_tasks: setup_helm_repo.yml

- name: Setup namespace
  ansible.builtin.include_tasks: setup_namespace.yml

- name: Create CA bundle
  ansible.builtin.include_tasks: create_bundle_ca.yml

- name: Setup TLS secret
  ansible.builtin.include_tasks: setup_tls_secret.yml

- name: Install Vault
  ansible.builtin.include_tasks: install_vault.yml

- name: Cleanup temporary files
  ansible.builtin.include_tasks: cleanup.yml
