---
# Setup kubeconfig for VM users and copy to localhost playbook directory
# This will create a 'kubeconfig' file in the directory where the playbook is executed
# Subsequent tasks can use this kubeconfig by setting the KUBECONFIG environment variable
# Example: KUBECONFIG={{ playbook_dir }}/kubeconfig kubectl get nodes

- name: Setup kubeconfig for users
  hosts: all
  become: true
  roles:
    - role: setup_kubeconfig
