---
# Setup kubeconfig for VM users and optionally copy to localhost
# To copy kubeconfig to localhost, pass the 'kubeconfig_host_name' variable when importing this playbook:
#   ansible.builtin.import_playbook: setup-kubeconfig-playbook.yml
#   vars:
#     kubeconfig_host_name: rancher-cluster-myproject.yaml
# This will create ~/.kube/{kubeconfig_host_name} on localhost

- name: Setup kubeconfig for users
  hosts: all
  become: true
  roles:
    - role: setup_kubeconfig
