---
- name: Setup /etc/hosts file on remote nodes
  hosts: all
  become: true
  roles:
    - role: setup_etc_hosts

- name: Setup /etc/hosts file on host
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Confirme que deseja fazer o ajuste na sua m√°quina?"
      private: true
  roles:
    - role: setup_etc_hosts
