---
- name: Instalar o servidor NTP Chrony
  ansible.builtin.apt:
    name: chrony
    state: present

- name: Remove todas entradas pool*
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    state: absent
    regexp: '^pool\s+.*'

- name: Adiciona pool do ntp.br
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    line: 'pool a.st1.ntp.br iburst maxsources 4'
    insertafter: EOF

- name: Reinicia o servi√ßo chrony
  ansible.builtin.service:
    name: chrony
    state: restarted
